import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

const Links = [
  {
    href : "/" , label : "Home"
  },
  {
    href : "/docs" , label : "Docs"
  },
  {
    href : "/todos" , label : "Todos"
  }
]

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <header>
        <nav>
          <ul className="flex items-center gap-5">
            {Links.map(link=>( 
              <li key={link.href}>
                <Link href={link.href}>{link.label}</Link>
              </li>
            ))}
          </ul>
        </nav>
      </header>
      {children}</body>
    </html>
  );
}
